"""Tests de Layer y sus subclases (dcpub.models)."""

import unittest

from dcpub.models import (
    Layer, PhotoLayer, LogoLayer, TextLayer, BoxLayer, CTALayer, LineLayer, DotsLayer,
    LAYER_CLASSES, layer_from_dict,
)


class TestLayerSubclasses(unittest.TestCase):
    def test_layer_has_autogenerated_unique_id(self):
        a = Layer()
        b = Layer()
        self.assertTrue(a.id)
        self.assertNotEqual(a.id, b.id)

    def test_photo_layer_defaults(self):
        p = PhotoLayer(src="foto.jpg")
        self.assertEqual(p.type, "photo")
        self.assertEqual(p.fit, "cover")
        self.assertEqual(p.zoom, 1.0)
        self.assertEqual(p.offset_x, 0.0)
        self.assertEqual(p.offset_y, 0.0)
        self.assertEqual(p.adjust["brightness"], 1.0)
        self.assertEqual(p.adjust["contrast"], 1.0)
        self.assertEqual(p.adjust["saturation"], 1.0)
        self.assertEqual(p.adjust["warmth"], 0.0)
        self.assertEqual(p.adjust["sharpness"], 1.0)
        self.assertEqual(p.adjust["shadows"], 0.0)
        self.assertEqual(p.adjust["vignette"], 0.0)
        self.assertEqual(p.overlay["bottom_grad"], False)
        self.assertEqual(p.overlay["top_grad"], False)
        self.assertEqual(p.overlay["strength"], 0.0)

    def test_logo_layer_defaults(self):
        logo = LogoLayer(src="logo.png")
        self.assertEqual(logo.type, "logo")
        self.assertTrue(logo.keep_ratio)

    def test_text_layer_defaults(self):
        t = TextLayer(text="Hola", role="title", size=0.08)
        self.assertEqual(t.type, "text")
        self.assertEqual(t.text, "Hola")
        self.assertEqual(t.role, "title")
        self.assertEqual(t.size, 0.08)

    def test_text_layer_rich_text_defaults(self):
        t = TextLayer(text="Hola", role="title")
        self.assertEqual(t.font_family, "")
        self.assertFalse(t.bold)
        self.assertFalse(t.italic)
        self.assertFalse(t.underline)
        self.assertEqual(t.line_spacing, 0.0)
        self.assertEqual(t.letter_spacing, 0.0)
        self.assertFalse(t.stroke_on)
        self.assertEqual(t.stroke_width, 0.0)

    def test_box_layer_defaults(self):
        b = BoxLayer(text="desc", icon="planta", size=0.03)
        self.assertEqual(b.type, "box")
        self.assertEqual(b.icon, "planta")

    def test_box_layer_fill_and_text_color_defaults(self):
        from dcpub.constants import BOX_COLOR, BLANCO
        b = BoxLayer()
        self.assertEqual(b.fill, list(BOX_COLOR))
        self.assertEqual(b.text_color, list(BLANCO) + [255])

    def test_cta_layer_defaults(self):
        from dcpub.constants import BOX_COLOR, BLANCO
        c = CTALayer()
        self.assertEqual(c.type, "cta")
        self.assertEqual(c.text, "")
        self.assertEqual(c.fill, list(BOX_COLOR))
        self.assertEqual(c.text_color, list(BLANCO) + [255])

    def test_line_layer_defaults(self):
        from dcpub.constants import VERDE
        line = LineLayer()
        self.assertEqual(line.type, "line")
        self.assertEqual(line.length, 0.22)
        self.assertEqual(line.thickness, 0.003)
        self.assertEqual(line.color, list(VERDE) + [255])
        self.assertEqual(line.gap, 0.0)

    def test_layer_classes_registers_line(self):
        self.assertIs(LAYER_CLASSES["line"], LineLayer)


    def test_dots_layer_defaults(self):
        from dcpub.constants import VERDE
        dots = DotsLayer()
        self.assertEqual(dots.type, "dots")
        self.assertEqual(dots.color, list(VERDE) + [255])
        self.assertEqual(dots.spacing, 0.025)

    def test_layer_classes_registers_dots(self):
        self.assertIs(LAYER_CLASSES["dots"], DotsLayer)

    def test_to_dict_includes_all_fields(self):
        t = TextLayer(text="Hola", role="title")
        d = t.to_dict()
        self.assertEqual(d["text"], "Hola")
        self.assertEqual(d["role"], "title")
        self.assertIn("id", d)
        self.assertIn("x", d)


class TestLayerFromDict(unittest.TestCase):
    def test_round_trip_preserves_type_and_fields(self):
        original = PhotoLayer(
            name="Foto", src="foto.jpg", zoom=1.5,
            adjust={
                "brightness": 1.2,
                "contrast": 1.1,
                "saturation": 0.8,
                "warmth": 0.2,
                "sharpness": 1.4,
                "shadows": 0.1,
                "vignette": 0.3,
            },
            overlay={"bottom_grad": True, "top_grad": True, "strength": 0.4},
        )
        restored = layer_from_dict(original.to_dict())
        self.assertIsInstance(restored, PhotoLayer)
        self.assertEqual(restored.src, "foto.jpg")
        self.assertEqual(restored.zoom, 1.5)
        self.assertEqual(restored.adjust, original.adjust)
        self.assertEqual(restored.overlay, original.overlay)
        self.assertEqual(restored.id, original.id)

    def test_round_trip_each_subclass(self):
        layers = [
            PhotoLayer(src="a.jpg"),
            LogoLayer(src="logo.png"),
            TextLayer(text="T", role="subtitle", font_family="lato", bold=True,
                      italic=True, underline=True, line_spacing=1.4,
                      letter_spacing=0.05, stroke_on=True, stroke_width=0.02),
            BoxLayer(text="D", icon="corazón", fill=[1, 2, 3, 100],
                     text_color=[4, 5, 6, 200]),
            CTALayer(text="Reservá ahora", fill=[9, 9, 9, 200]),
            LineLayer(length=0.30, thickness=0.008, color=[7, 8, 9, 250], gap=0.05),
            DotsLayer(color=[10, 11, 12, 240], spacing=0.04),
        ]
        for layer in layers:
            restored = layer_from_dict(layer.to_dict())
            self.assertIs(type(restored), type(layer))
            self.assertEqual(restored.to_dict(), layer.to_dict())


if __name__ == "__main__":
    unittest.main()
