"""Tests de Layer y sus subclases (dcpub.models)."""

import unittest

from dcpub.models import (
    Layer, PhotoLayer, LogoLayer, TextLayer, BoxLayer, layer_from_dict,
)


class TestLayerSubclasses(unittest.TestCase):
    def test_layer_has_autogenerated_unique_id(self):
        a = Layer()
        b = Layer()
        self.assertTrue(a.id)
        self.assertNotEqual(a.id, b.id)

    def test_photo_layer_defaults(self):
        p = PhotoLayer(src="foto.jpg")
        self.assertEqual(p.type, "photo")
        self.assertEqual(p.fit, "cover")
        self.assertEqual(p.zoom, 1.0)
        self.assertEqual(p.offset_x, 0.0)
        self.assertEqual(p.offset_y, 0.0)

    def test_logo_layer_defaults(self):
        logo = LogoLayer(src="logo.png")
        self.assertEqual(logo.type, "logo")
        self.assertTrue(logo.keep_ratio)

    def test_text_layer_defaults(self):
        t = TextLayer(text="Hola", role="title", size=0.08)
        self.assertEqual(t.type, "text")
        self.assertEqual(t.text, "Hola")
        self.assertEqual(t.role, "title")
        self.assertEqual(t.size, 0.08)

    def test_box_layer_defaults(self):
        b = BoxLayer(text="desc", icon="planta", size=0.03)
        self.assertEqual(b.type, "box")
        self.assertEqual(b.icon, "planta")

    def test_to_dict_includes_all_fields(self):
        t = TextLayer(text="Hola", role="title")
        d = t.to_dict()
        self.assertEqual(d["text"], "Hola")
        self.assertEqual(d["role"], "title")
        self.assertIn("id", d)
        self.assertIn("x", d)


class TestLayerFromDict(unittest.TestCase):
    def test_round_trip_preserves_type_and_fields(self):
        original = PhotoLayer(name="Foto", src="foto.jpg", zoom=1.5)
        restored = layer_from_dict(original.to_dict())
        self.assertIsInstance(restored, PhotoLayer)
        self.assertEqual(restored.src, "foto.jpg")
        self.assertEqual(restored.zoom, 1.5)
        self.assertEqual(restored.id, original.id)

    def test_round_trip_each_subclass(self):
        layers = [
            PhotoLayer(src="a.jpg"),
            LogoLayer(src="logo.png"),
            TextLayer(text="T", role="subtitle"),
            BoxLayer(text="D", icon="corazón"),
        ]
        for layer in layers:
            restored = layer_from_dict(layer.to_dict())
            self.assertIs(type(restored), type(layer))
            self.assertEqual(restored.to_dict(), layer.to_dict())


if __name__ == "__main__":
    unittest.main()
